[env]
TERM = "screen-256color"

[font]
size = 16

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 1.0
decorations = "none"
dynamic_padding = false

[window.padding]
x = 0
y = 0

[general]
import = ["themes/vague.toml"]
